import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Generates the data behind /examples: one card per form that has a real
// examples/personas.json (hand-curated, engine-verified scenarios — see
// AGENTS.md's "bin/test-personas" tooling), showing its title, lead
// description, and persona names/descriptions. Forms with no personas
// (the 3 fleet-wide that are genuinely engine-less by design — pure
// documentation/notice forms with no scoring, grading, or validation) are
// correctly excluded rather than shown with an empty card.

const __dirname = dirname(fileURLToPath(import.meta.url));
const FORMS_DIR = resolve(__dirname, '..', '..', 'forms');
const OUT_PATH = resolve(__dirname, '..', 'src', 'lib', 'data', 'examples.generated.ts');

type Persona = { name: string; description: string };
type ExampleEntry = { slug: string; title: string; description: string; personas: Persona[] };

function humanizeSlug(slug: string): string {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Strip the lightest Markdown emphasis markers so the lead paragraph reads
// as plain prose on a card (bold/italic within a fixed-width teaser reads
// as stray asterisks otherwise).
function stripMarkdownEmphasis(text: string): string {
  return text.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\*([^*]+)\*/g, '$1');
}

function readTitleAndDescription(slug: string): { title: string; description: string } {
  const indexPath = join(FORMS_DIR, slug, 'index.md');
  let title = humanizeSlug(slug);
  let description = '';
  try {
    const content = readFileSync(indexPath, 'utf-8');
    const titleMatch = content.match(/^#\s+(.+)$/m);
    if (titleMatch) title = titleMatch[1].trim();

    // The lead paragraph: the first non-empty, non-heading run of lines
    // after the title, up to the next blank line.
    const lines = content.split('\n');
    const titleLine = lines.findIndex((l) => /^#\s+/.test(l));
    const paragraphLines: string[] = [];
    let started = false;
    for (let i = titleLine + 1; i < lines.length; i++) {
      const line = lines[i];
      if (!started) {
        if (line.trim() === '') continue;
        if (/^#/.test(line)) break;
        started = true;
      }
      if (line.trim() === '') break;
      if (/^#/.test(line)) break;
      paragraphLines.push(line);
    }
    description = stripMarkdownEmphasis(paragraphLines.join(' ').trim());
  } catch {
    // index.md missing or unreadable — fall through with defaults.
  }
  return { title, description };
}

function readPersonas(slug: string): Persona[] {
  const path = join(FORMS_DIR, slug, 'examples', 'personas.json');
  try {
    const raw = JSON.parse(readFileSync(path, 'utf-8'));
    const personas = Array.isArray(raw.personas) ? raw.personas : [];
    return personas
      .map((p: unknown) => {
        const persona = p as { name?: unknown; description?: unknown };
        return {
          name: typeof persona.name === 'string' ? persona.name : '',
          description: typeof persona.description === 'string' ? persona.description : ''
        };
      })
      .filter((p: Persona) => p.name);
  } catch {
    return [];
  }
}

function main() {
  let entries: string[];
  try {
    entries = readdirSync(FORMS_DIR);
  } catch {
    // Standalone checkout with no sibling forms/ (see generate-forms-data.ts
    // for the full explanation) — keep the committed data as-is.
    console.log(`${FORMS_DIR} not found — standalone checkout, keeping committed examples.generated.ts`);
    return;
  }

  const out: ExampleEntry[] = [];
  for (const entry of entries) {
    const fullPath = join(FORMS_DIR, entry);
    let isDir = false;
    try {
      isDir = statSync(fullPath).isDirectory();
    } catch {
      continue;
    }
    if (!isDir || entry.startsWith('.')) continue;
    try {
      statSync(join(fullPath, 'index.md'));
    } catch {
      continue;
    }

    const personas = readPersonas(entry);
    if (personas.length === 0) continue; // no personas.json, or genuinely engine-less form

    const { title, description } = readTitleAndDescription(entry);
    out.push({ slug: entry, title, description, personas });
  }

  out.sort((a, b) => a.slug.localeCompare(b.slug));

  const body = `// AUTO-GENERATED by scripts/generate-examples-data.ts. Do not edit by hand.

export type Persona = { name: string; description: string };
export type ExampleEntry = { slug: string; title: string; description: string; personas: Persona[] };

export const examples: ExampleEntry[] = ${JSON.stringify(out, null, 2)};
`;

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, body, 'utf-8');
  const totalPersonas = out.reduce((sum, e) => sum + e.personas.length, 0);
  console.log(`Generated ${out.length} example card(s), ${totalPersonas} persona(s) total → ${OUT_PATH}`);
}

main();
