import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FORMS_DIR = resolve(__dirname, '..', '..', 'forms');
const OUT_PATH = resolve(__dirname, '..', 'src', 'lib', 'data', 'forms.generated.ts');

type Form = { slug: string; title: string };

function humanizeSlug(slug: string): string {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function readTitle(slug: string): string {
  const indexPath = join(FORMS_DIR, slug, 'index.md');
  try {
    const content = readFileSync(indexPath, 'utf-8');
    const match = content.match(/^#\s+(.+)$/m);
    if (match) return match[1].trim();
  } catch {
    // index.md missing or unreadable — fall through
  }
  return humanizeSlug(slug);
}

function main() {
  const entries = readdirSync(FORMS_DIR);
  const forms: Form[] = [];

  for (const entry of entries) {
    const fullPath = join(FORMS_DIR, entry);
    let isDir = false;
    try {
      isDir = statSync(fullPath).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;
    if (entry.startsWith('.')) continue;
    forms.push({ slug: entry, title: readTitle(entry) });
  }

  forms.sort((a, b) => a.slug.localeCompare(b.slug));

  const body = `// AUTO-GENERATED by scripts/generate-forms-data.ts. Do not edit by hand.\n\nexport type Form = { slug: string; title: string };\n\nexport const forms: Form[] = ${JSON.stringify(forms, null, 2)};\n`;

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, body, 'utf-8');
  console.log(`Generated ${forms.length} forms → ${OUT_PATH}`);
}

main();
