// AUTO-GENERATED by scripts/generate-forms-data.ts. Do not edit by hand.

export type Form = { slug: string; title: string };

export const forms: Form[] = [
  {
    "slug": "abdominal-aortic-aneurysm-screening",
    "title": "Abdominal Aortic Aneurysm (AAA) Screening"
  },
  {
    "slug": "accident-and-emergency-medicine-waiting-list-card",
    "title": "Accident and Emergency Medicine Waiting List Card"
  },
  {
    "slug": "advance-decision-to-refuse-treatment",
    "title": "Advance Decision to Refuse Treatment"
  },
  {
    "slug": "advance-statement-about-care",
    "title": "Advance Statement About Care"
  },
  {
    "slug": "agile-checklist",
    "title": "Agile Checklist"
  },
  {
    "slug": "agile-consulting-scorecard-for-hiring-help",
    "title": "Agile consulting scorecard for hiring help"
  },
  {
    "slug": "agile-principles-assessment",
    "title": "Agile Principles Assessment"
  },
  {
    "slug": "alcohol-use-disorders-identification-test-consumption",
    "title": "Alcohol Use Disorders Identification Test — Consumption (AUDIT-C)"
  },
  {
    "slug": "allergist-waiting-list-card",
    "title": "Allergist Waiting List Card"
  },
  {
    "slug": "allergy-assessment",
    "title": "Allergy Assessment"
  },
  {
    "slug": "allergy-skin-test-request",
    "title": "Allergy Skin Test Request"
  },
  {
    "slug": "allergy-skin-test-result",
    "title": "Allergy Skin Test Result"
  },
  {
    "slug": "ambulatory-blood-pressure-test-request",
    "title": "Ambulatory Blood Pressure Test Request"
  },
  {
    "slug": "ambulatory-blood-pressure-test-result",
    "title": "Ambulatory Blood Pressure Test Result"
  },
  {
    "slug": "anaesthetic-record",
    "title": "Anaesthetic Record"
  },
  {
    "slug": "anaesthetics-waiting-list-card",
    "title": "Anaesthetics Waiting List Card"
  },
  {
    "slug": "anesthesiology-assessment",
    "title": "Anesthesiology Assessment"
  },
  {
    "slug": "angiography-test-request",
    "title": "Angiography Test Request"
  },
  {
    "slug": "angiography-test-result",
    "title": "Angiography Test Result"
  },
  {
    "slug": "anion-gap-calculator",
    "title": "Anion Gap Calculator"
  },
  {
    "slug": "apgar-score",
    "title": "Apgar Score"
  },
  {
    "slug": "arc42",
    "title": "arc42"
  },
  {
    "slug": "architecture-decision-record",
    "title": "Architecture Decision Record (Tyree & Akerman)"
  },
  {
    "slug": "asthma-assessment",
    "title": "Asthma Assessment"
  },
  {
    "slug": "attention-deficit-assessment",
    "title": "Attention Deficit Assessment"
  },
  {
    "slug": "audio-vestibular-assessment",
    "title": "Audio-Vestibular Assessment"
  },
  {
    "slug": "audiology-assessment",
    "title": "Audiology Assessment"
  },
  {
    "slug": "autism-assessment",
    "title": "Autism Assessment"
  },
  {
    "slug": "bhutani-bilirubin-nomogram",
    "title": "Bhutani Bilirubin Nomogram"
  },
  {
    "slug": "biopsy-test-request",
    "title": "Biopsy Test Request"
  },
  {
    "slug": "biopsy-test-result",
    "title": "Biopsy Test Result"
  },
  {
    "slug": "birth-control-assessment",
    "title": "Birth Control Assessment"
  },
  {
    "slug": "blood-cross-match-test-request",
    "title": "Blood Cross-Match Test Request"
  },
  {
    "slug": "blood-cross-match-test-result",
    "title": "Blood Cross-Match Test Result"
  },
  {
    "slug": "blood-donation-assessment",
    "title": "Blood Donation Assessment"
  },
  {
    "slug": "blood-test-request",
    "title": "Blood Test Request"
  },
  {
    "slug": "blood-test-result",
    "title": "Blood Test Result"
  },
  {
    "slug": "body-mass-index-and-body-surface-area-calculator",
    "title": "Body Mass Index and Body Surface Area Calculator"
  },
  {
    "slug": "bone-marrow-donation-assessment",
    "title": "Bone Marrow Donation Assessment"
  },
  {
    "slug": "bowel-cancer-screening-with-faecal-immunochemical-test",
    "title": "Bowel Cancer Screening with Faecal Immunochemical Test (FIT)"
  },
  {
    "slug": "breast-screening",
    "title": "Breast Screening Record (NHS Breast Screening Programme)"
  },
  {
    "slug": "bronchoscopy-test-request",
    "title": "Bronchoscopy Test Request"
  },
  {
    "slug": "bronchoscopy-test-result",
    "title": "Bronchoscopy Test Result"
  },
  {
    "slug": "cage-alcohol-questionnaire",
    "title": "CAGE Alcohol Questionnaire"
  },
  {
    "slug": "caprini-venous-thromboembolism-risk-assessment",
    "title": "Caprini Venous Thromboembolism Risk Assessment"
  },
  {
    "slug": "cardiac-stress-test-request",
    "title": "Cardiac Stress Test Request"
  },
  {
    "slug": "cardiac-stress-test-result",
    "title": "Cardiac Stress Test Result"
  },
  {
    "slug": "cardiology-assessment",
    "title": "Cardiology Assessment"
  },
  {
    "slug": "cardiology-request",
    "title": "Cardiology Request"
  },
  {
    "slug": "cardiology-response",
    "title": "Cardiology Response"
  },
  {
    "slug": "cardiology-waiting-list-card",
    "title": "Cardiology Waiting List Card"
  },
  {
    "slug": "cardiopulmonary-resuscitation-training",
    "title": "Cardiopulmonary Resuscitation Training"
  },
  {
    "slug": "care-privacy-notice",
    "title": "Care Privacy Notice"
  },
  {
    "slug": "casualty-card-form",
    "title": "Casualty Card Form"
  },
  {
    "slug": "cataract-diagnostic-evaluation",
    "title": "Cataract Diagnostic Evaluation"
  },
  {
    "slug": "centor-score-for-streptococcal-pharyngitis",
    "title": "Centor Score for Streptococcal Pharyngitis"
  },
  {
    "slug": "cervical-screening",
    "title": "Cervical Screening record"
  },
  {
    "slug": "cha2ds2-vasc-score-for-atrial-fibrillation-stroke-risk",
    "title": "CHA2DS2-VASc Score for Atrial Fibrillation Stroke Risk"
  },
  {
    "slug": "child-psychiatry-waiting-list-card",
    "title": "Child Psychiatry Waiting List Card"
  },
  {
    "slug": "child-pugh-score",
    "title": "Child-Pugh Score (Child-Turcotte-Pugh)"
  },
  {
    "slug": "child-safeguarding-referral",
    "title": "Child Safeguarding Referral"
  },
  {
    "slug": "chronic-kidney-disease-review",
    "title": "Chronic Kidney Disease Annual Review"
  },
  {
    "slug": "chronic-obstructive-pulmonary-disease-review",
    "title": "Chronic Obstructive Pulmonary Disease Review (COPD Annual Review)"
  },
  {
    "slug": "clinical-biology-waiting-list-card",
    "title": "Clinical Biology Waiting List Card"
  },
  {
    "slug": "clinical-chemistry-waiting-list-card",
    "title": "Clinical Chemistry Waiting List Card"
  },
  {
    "slug": "clinical-microbiology-waiting-list-card",
    "title": "Clinical Microbiology Waiting List Card"
  },
  {
    "slug": "clinical-neurophysiology-waiting-list-card",
    "title": "Clinical Neurophysiology Waiting List Card"
  },
  {
    "slug": "coagulation-test-request",
    "title": "Coagulation Test Request"
  },
  {
    "slug": "coagulation-test-result",
    "title": "Coagulation Test Result"
  },
  {
    "slug": "code-of-conduct-notice",
    "title": "Code of Conduct Notice"
  },
  {
    "slug": "cognitive-assessment",
    "title": "Cognitive Assessment"
  },
  {
    "slug": "colonoscopy-test-request",
    "title": "Colonoscopy Test Request"
  },
  {
    "slug": "colonoscopy-test-result",
    "title": "Colonoscopy Test Result"
  },
  {
    "slug": "columbia-suicide-severity-rating-scale",
    "title": "Columbia Suicide Severity Rating Scale (C-SSRS)"
  },
  {
    "slug": "confusion-assessment-method",
    "title": "Confusion Assessment Method (CAM)"
  },
  {
    "slug": "consent-to-treatment",
    "title": "Consent to Treatment"
  },
  {
    "slug": "contraception-assessment",
    "title": "Contraception Assessment"
  },
  {
    "slug": "corrected-calcium-calculator",
    "title": "Corrected Calcium Calculator"
  },
  {
    "slug": "craniofacial-surgery-waiting-list-card",
    "title": "Craniofacial Surgery Waiting List Card"
  },
  {
    "slug": "ct-scan-test-request",
    "title": "CT Scan Test Request"
  },
  {
    "slug": "ct-scan-test-result",
    "title": "CT Scan Test Result"
  },
  {
    "slug": "curb-65-pneumonia-severity-score",
    "title": "CURB-65 Pneumonia Severity Score"
  },
  {
    "slug": "cystoscopy-test-request",
    "title": "Cystoscopy Test Request"
  },
  {
    "slug": "cystoscopy-test-result",
    "title": "Cystoscopy Test Result"
  },
  {
    "slug": "cytology-test-request",
    "title": "Cytology Test Request"
  },
  {
    "slug": "cytology-test-result",
    "title": "Cytology Test Result"
  },
  {
    "slug": "dental-assessment",
    "title": "Dental Assessment"
  },
  {
    "slug": "dermatology-assessment",
    "title": "Dermatology Assessment"
  },
  {
    "slug": "dermatology-waiting-list-card",
    "title": "Dermatology Waiting List Card"
  },
  {
    "slug": "dexa-bone-density-test-request",
    "title": "DEXA Bone Density Test Request"
  },
  {
    "slug": "dexa-bone-density-test-result",
    "title": "DEXA Bone Density Test Result"
  },
  {
    "slug": "diabetes-assessment",
    "title": "Diabetes Assessment"
  },
  {
    "slug": "diabetic-eye-screening",
    "title": "Diabetic Eye Screening record"
  },
  {
    "slug": "dietic-assessment",
    "title": "Dietetic Assessment"
  },
  {
    "slug": "dyslexia-assessment",
    "title": "Dyslexia Assessment"
  },
  {
    "slug": "echocardiogram-test-request",
    "title": "Echocardiogram Test Request"
  },
  {
    "slug": "echocardiogram-test-result",
    "title": "Echocardiogram Test Result"
  },
  {
    "slug": "edinburgh-postnatal-depression-scale",
    "title": "Edinburgh Postnatal Depression Scale (EPDS)"
  },
  {
    "slug": "electrocardiogram-test-request",
    "title": "Electrocardiogram Test Request"
  },
  {
    "slug": "electrocardiogram-test-result",
    "title": "Electrocardiogram Test Result"
  },
  {
    "slug": "electroencephalogram-test-request",
    "title": "Electroencephalogram Test Request"
  },
  {
    "slug": "electroencephalogram-test-result",
    "title": "Electroencephalogram Test Result"
  },
  {
    "slug": "emergency-department-triage-note",
    "title": "Emergency Department Triage Note"
  },
  {
    "slug": "emergency-medical-technician-psychomotor-examination",
    "title": "Emergency Medical Technician Psychomotor Examination"
  },
  {
    "slug": "employee-offboarding-checklist",
    "title": "Employee Offboarding Checklist"
  },
  {
    "slug": "employee-onboarding-checklist",
    "title": "Employee Onboarding Checklist"
  },
  {
    "slug": "employee-satisfaction-survey",
    "title": "Employee Satisfaction Survey"
  },
  {
    "slug": "encounter-satisfaction",
    "title": "Encounter Satisfaction"
  },
  {
    "slug": "endocrinology-assessment",
    "title": "Endocrinology Assessment"
  },
  {
    "slug": "endocrinology-waiting-list-card",
    "title": "Endocrinology Waiting List Card"
  },
  {
    "slug": "endometriosis-assessment",
    "title": "Endometriosis Assessment"
  },
  {
    "slug": "endoscopy-test-request",
    "title": "Endoscopy Test Request"
  },
  {
    "slug": "epilepsy-review",
    "title": "Epilepsy Annual Review"
  },
  {
    "slug": "ergonomic-assessment",
    "title": "Ergonomic Assessment"
  },
  {
    "slug": "estimated-glomerular-filtration-rate-calculator",
    "title": "Estimated Glomerular Filtration Rate (eGFR) Calculator"
  },
  {
    "slug": "eye-prescription",
    "title": "Eye Prescription"
  },
  {
    "slug": "eye-vision-test-request",
    "title": "Eye Vision Test Request"
  },
  {
    "slug": "eye-vision-test-result",
    "title": "Eye Vision Test Result"
  },
  {
    "slug": "fall-risk-assessment",
    "title": "Fall Risk Assessment"
  },
  {
    "slug": "family-and-general-medicine-waiting-list-card",
    "title": "Family and General Medicine Waiting List Card"
  },
  {
    "slug": "fertility-assessment",
    "title": "Fertility Assessment"
  },
  {
    "slug": "first-aid-training-checklist",
    "title": "First Aid Training Checklist"
  },
  {
    "slug": "first-responder-assessment",
    "title": "First Responder Assessment"
  },
  {
    "slug": "fluid-balance-chart",
    "title": "Fluid Balance Chart"
  },
  {
    "slug": "fluoroscopy-test-request",
    "title": "Fluoroscopy Test Request"
  },
  {
    "slug": "fluoroscopy-test-result",
    "title": "Fluoroscopy Test Result"
  },
  {
    "slug": "four-a-test-for-delirium",
    "title": "4AT — Rapid Delirium and Cognitive-Impairment Screen"
  },
  {
    "slug": "framingham-risk-score-for-hard-coronary-heart-disease",
    "title": "Framingham Risk Score for Hard Coronary Heart Disease"
  },
  {
    "slug": "gastroenterologic-surgery-waiting-list-card",
    "title": "Gastroenterologic Surgery Waiting List Card"
  },
  {
    "slug": "gastroenterology-assessment",
    "title": "Gastroenterology Assessment"
  },
  {
    "slug": "gastroenterology-waiting-list-card",
    "title": "Gastroenterology Waiting List Card"
  },
  {
    "slug": "general-practice-waiting-list-card",
    "title": "General Practice Waiting List Card"
  },
  {
    "slug": "general-practitioner-referral-letter",
    "title": "General Practitioner Referral Letter"
  },
  {
    "slug": "general-surgery-waiting-list-card",
    "title": "General Surgery Waiting List Card"
  },
  {
    "slug": "genetic-assessment",
    "title": "Genetic Assessment"
  },
  {
    "slug": "genetic-test-request",
    "title": "Genetic Test Request"
  },
  {
    "slug": "genetic-test-result",
    "title": "Genetic Test Result"
  },
  {
    "slug": "genetics-assessment",
    "title": "Genetics Assessment"
  },
  {
    "slug": "geriatrics-waiting-list-card",
    "title": "Geriatrics Waiting List Card"
  },
  {
    "slug": "gerontology-assessment",
    "title": "Gerontology Assessment"
  },
  {
    "slug": "glasgow-blatchford-bleeding-score",
    "title": "Glasgow-Blatchford Bleeding Score (GBS)"
  },
  {
    "slug": "glasgow-coma-scale",
    "title": "Glasgow Coma Scale"
  },
  {
    "slug": "grace-score-for-acute-coronary-syndrome",
    "title": "GRACE Score for Acute Coronary Syndrome"
  },
  {
    "slug": "gynecology-assessment",
    "title": "Gynecology Assessment"
  },
  {
    "slug": "has-bled-score-for-major-bleeding-risk",
    "title": "HAS-BLED Score for Major Bleeding Risk"
  },
  {
    "slug": "health-screening-questionnaire",
    "title": "Health Screening Questionnaire"
  },
  {
    "slug": "hearing-aid-assessment",
    "title": "Hearing Aid Assessment"
  },
  {
    "slug": "hearing-test-request",
    "title": "Hearing Test Request"
  },
  {
    "slug": "hearing-test-result",
    "title": "Hearing Test Result"
  },
  {
    "slug": "heart-failure-review",
    "title": "Heart Failure Annual Review"
  },
  {
    "slug": "heart-health-check",
    "title": "Heart Health Check"
  },
  {
    "slug": "hematology-assessment",
    "title": "Hematology Assessment"
  },
  {
    "slug": "hematology-waiting-list-card",
    "title": "Hematology Waiting List Card"
  },
  {
    "slug": "hernia-diagnostic-evaluation",
    "title": "Hernia Diagnostic Evaluation"
  },
  {
    "slug": "hip-replacement-surgery-evaluation",
    "title": "Hip Replacement Surgery Evaluation"
  },
  {
    "slug": "histopathology-test-request",
    "title": "Histopathology Test Request"
  },
  {
    "slug": "histopathology-test-result",
    "title": "Histopathology Test Result"
  },
  {
    "slug": "history-and-physical-examination",
    "title": "History and Physical Examination (H&P)"
  },
  {
    "slug": "holter-monitor-test-request",
    "title": "Holter Monitor Test Request"
  },
  {
    "slug": "holter-monitor-test-result",
    "title": "Holter Monitor Test Result"
  },
  {
    "slug": "hormone-replacement-therapy-assessment",
    "title": "Hormone Replacement Therapy Assessment"
  },
  {
    "slug": "hospital-daily-monitoring-checklist",
    "title": "Hospital Daily Monitoring Checklist"
  },
  {
    "slug": "hospital-dashboard-metrics",
    "title": "Hospital Dashboard Metrics"
  },
  {
    "slug": "hospital-discharge",
    "title": "Hospital Discharge"
  },
  {
    "slug": "hospital-performance-indicators",
    "title": "Hospital Performance Indicators"
  },
  {
    "slug": "hypertension-review",
    "title": "Hypertension Annual Review"
  },
  {
    "slug": "immunology-waiting-list-card",
    "title": "Immunology Waiting List Card"
  },
  {
    "slug": "infectious-diseases-waiting-list-card",
    "title": "Infectious Diseases Waiting List Card"
  },
  {
    "slug": "inpatient-clinical-note",
    "title": "Inpatient Clinical Note"
  },
  {
    "slug": "integumentary-assessment",
    "title": "Integumentary Assessment"
  },
  {
    "slug": "internal-medicine-waiting-list-card",
    "title": "Internal Medicine Waiting List Card"
  },
  {
    "slug": "international-certificate-of-vaccination-or-prophylaxis",
    "title": "International Certificate of Vaccination or Prophylaxis (ICVP)"
  },
  {
    "slug": "international-patient-summary",
    "title": "International Patient Summary"
  },
  {
    "slug": "issue-tracker",
    "title": "Issue tracker"
  },
  {
    "slug": "kinesiology-assessment",
    "title": "Kinesiology Assessment"
  },
  {
    "slug": "knee-replacement-surgery-evaluation",
    "title": "Knee Replacement Surgery Evaluation"
  },
  {
    "slug": "laboratory-medicine-waiting-list-card",
    "title": "Laboratory Medicine Waiting List Card"
  },
  {
    "slug": "learning-disability-annual-health-check",
    "title": "Learning Disability Annual Health Check"
  },
  {
    "slug": "learning-disability-assessment",
    "title": "Learning Disability Assessment"
  },
  {
    "slug": "legal-requirements-privacy-notice",
    "title": "Legal Requirements Privacy Notice"
  },
  {
    "slug": "lifeguard-certification-checklist",
    "title": "Lifeguard Certification Checklist"
  },
  {
    "slug": "lumbar-puncture-test-request",
    "title": "Lumbar Puncture Test Request"
  },
  {
    "slug": "lumbar-puncture-test-result",
    "title": "Lumbar Puncture Test Result"
  },
  {
    "slug": "mammography-test-request",
    "title": "Mammography Test Request"
  },
  {
    "slug": "mammography-test-result",
    "title": "Mammography Test Result"
  },
  {
    "slug": "mast-cell-activation-syndrome-assessment",
    "title": "Mast Cell Activation Syndrome (MCAS) Assessment"
  },
  {
    "slug": "medical-certificate-of-cause-of-death",
    "title": "Medical Certificate of Cause of Death (MCCD)"
  },
  {
    "slug": "medical-error-report",
    "title": "Medical Error Report"
  },
  {
    "slug": "medical-information-form-for-air-travel",
    "title": "Medical Information Form for Air Travel (MEDIF)"
  },
  {
    "slug": "medical-language-speaking-assessment-for-cymraeg",
    "title": "Medical Language Speaking Assessment for Cymraeg"
  },
  {
    "slug": "medical-language-speaking-assessment-for-english",
    "title": "Medical Language Speaking Assessment for English"
  },
  {
    "slug": "medical-operation-note",
    "title": "Medical Operation Note"
  },
  {
    "slug": "medical-records-release-permission",
    "title": "Medical Records Release Permission"
  },
  {
    "slug": "medical-waiting-list-card",
    "title": "Medical Waiting List Card"
  },
  {
    "slug": "medication-reconciliation",
    "title": "Medication Reconciliation"
  },
  {
    "slug": "meeting",
    "title": "Meeting"
  },
  {
    "slug": "mental-health-act-assessment",
    "title": "Mental Health Act Assessment"
  },
  {
    "slug": "mental-health-assessment",
    "title": "Mental Health Assessment"
  },
  {
    "slug": "mental-state-examination",
    "title": "Mental State Examination (MSE)"
  },
  {
    "slug": "microbiology-culture-test-request",
    "title": "Microbiology Culture Test Request"
  },
  {
    "slug": "microbiology-culture-test-result",
    "title": "Microbiology Culture Test Result"
  },
  {
    "slug": "mobility-assessment",
    "title": "Mobility Assessment"
  },
  {
    "slug": "model-for-end-stage-liver-disease-score",
    "title": "Model for End-Stage Liver Disease (MELD) Score"
  },
  {
    "slug": "modified-early-warning-score",
    "title": "Modified Early Warning Score (MEWS)"
  },
  {
    "slug": "mri-scan-test-request",
    "title": "MRI Scan Test Request"
  },
  {
    "slug": "mri-scan-test-result",
    "title": "MRI Scan Test Result"
  },
  {
    "slug": "national-early-warning-score-2",
    "title": "National Early Warning Score 2 (NEWS2)"
  },
  {
    "slug": "nephrology-waiting-list-card",
    "title": "Nephrology Waiting List Card"
  },
  {
    "slug": "nerve-conduction-study-test-request",
    "title": "Nerve Conduction Study Test Request"
  },
  {
    "slug": "nerve-conduction-study-test-result",
    "title": "Nerve Conduction Study Test Result"
  },
  {
    "slug": "neurodiversity-adjustment-request",
    "title": "Neurodiversity Adjustment Request"
  },
  {
    "slug": "neurodiversity-adjustment-response",
    "title": "Neurodiversity Adjustment Response"
  },
  {
    "slug": "neurodiversity-adjustment-review",
    "title": "Neurodiversity Adjustment Review"
  },
  {
    "slug": "neurology-assessment",
    "title": "Neurology Assessment"
  },
  {
    "slug": "neurology-waiting-list-card",
    "title": "Neurology Waiting List Card"
  },
  {
    "slug": "neuropsychiatry-waiting-list-card",
    "title": "Neuropsychiatry Waiting List Card"
  },
  {
    "slug": "neurosurgery-waiting-list-card",
    "title": "Neurosurgery Waiting List Card"
  },
  {
    "slug": "newborn-and-infant-physical-examination",
    "title": "Newborn and Infant Physical Examination (NIPE)"
  },
  {
    "slug": "newborn-blood-spot-screening",
    "title": "Newborn Blood Spot Screening"
  },
  {
    "slug": "nuclear-medicine-test-request",
    "title": "Nuclear Medicine Test Request"
  },
  {
    "slug": "nuclear-medicine-test-result",
    "title": "Nuclear Medicine Test Result"
  },
  {
    "slug": "nuclear-medicine-waiting-list-card",
    "title": "Nuclear Medicine Waiting List Card"
  },
  {
    "slug": "nursing-care-plan",
    "title": "Nursing Care Plan"
  },
  {
    "slug": "nutrition-assessment",
    "title": "Nutrition Assessment"
  },
  {
    "slug": "objectives-and-key-results-tracker",
    "title": "Objectives and Key Results tracker"
  },
  {
    "slug": "obstetrics-and-gynaecology-waiting-list-card",
    "title": "Obstetrics and Gynaecology Waiting List Card"
  },
  {
    "slug": "obstetrics-assessment",
    "title": "Obstetrics Assessment"
  },
  {
    "slug": "occupational-medicine-waiting-list-card",
    "title": "Occupational Medicine Waiting List Card"
  },
  {
    "slug": "occupational-therapy-assessment",
    "title": "Occupational Therapy Assessment"
  },
  {
    "slug": "oncology-assessment",
    "title": "Oncology Assessment"
  },
  {
    "slug": "oncology-waiting-list-card",
    "title": "Oncology Waiting List Card"
  },
  {
    "slug": "ophthalmology-assessment",
    "title": "Ophthalmology Assessment"
  },
  {
    "slug": "ophthalmology-waiting-list-card",
    "title": "Ophthalmology Waiting List Card"
  },
  {
    "slug": "oral-and-maxillofacial-surgery-waiting-list-card",
    "title": "Oral and Maxillofacial Surgery Waiting List Card"
  },
  {
    "slug": "organ-donation-assessment",
    "title": "Organ Donation Assessment"
  },
  {
    "slug": "orthopaedics-waiting-list-card",
    "title": "Orthopaedics Waiting List Card"
  },
  {
    "slug": "orthopedic-assessment",
    "title": "Orthopaedic Assessment"
  },
  {
    "slug": "otolaryngology-assessment",
    "title": "Otolaryngology Assessment"
  },
  {
    "slug": "otorhinolaryngology-waiting-list-card",
    "title": "Otorhinolaryngology Waiting List Card"
  },
  {
    "slug": "ottawa-ankle-rules",
    "title": "Ottawa Ankle Rules (and Ottawa Foot Rules)"
  },
  {
    "slug": "ottawa-knee-rule",
    "title": "Ottawa Knee Rule"
  },
  {
    "slug": "outpatient-outcome",
    "title": "Outpatient Outcome Report"
  },
  {
    "slug": "padua-venous-thromboembolism-risk-assessment",
    "title": "Padua Venous Thromboembolism Risk Assessment (Padua Prediction Score)"
  },
  {
    "slug": "paediatric-early-warning-score",
    "title": "Paediatric Early Warning Score (PEWS)"
  },
  {
    "slug": "paediatric-surgery-waiting-list-card",
    "title": "Paediatric Surgery Waiting List Card"
  },
  {
    "slug": "paediatrics-waiting-list-card",
    "title": "Paediatrics Waiting List Card"
  },
  {
    "slug": "palliative-assessment",
    "title": "Palliative Assessment"
  },
  {
    "slug": "parkland-formula-for-burns",
    "title": "Parkland Formula for Burns"
  },
  {
    "slug": "partogram",
    "title": "Partogram (Partograph)"
  },
  {
    "slug": "pathology-waiting-list-card",
    "title": "Pathology Waiting List Card"
  },
  {
    "slug": "patient-intake",
    "title": "Patient Intake"
  },
  {
    "slug": "patient-reported-outcome-measures",
    "title": "Patient-Reported Outcome Measures"
  },
  {
    "slug": "patient-room-readiness",
    "title": "Patient Room Readiness"
  },
  {
    "slug": "patient-satisfaction-survey",
    "title": "Patient Satisfaction Survey"
  },
  {
    "slug": "pediatric-assessment",
    "title": "Pediatric Assessment"
  },
  {
    "slug": "perioperative-optimization",
    "title": "Perioperative Optimization"
  },
  {
    "slug": "pet-scan-test-request",
    "title": "PET Scan Test Request"
  },
  {
    "slug": "pet-scan-test-result",
    "title": "PET Scan Test Result"
  },
  {
    "slug": "pharmacology-waiting-list-card",
    "title": "Pharmacology Waiting List Card"
  },
  {
    "slug": "physical-medicine-and-rehabilitation-waiting-list-card",
    "title": "Physical Medicine and Rehabilitation Waiting List Card"
  },
  {
    "slug": "plastic-surgery-assessment",
    "title": "Plastic Surgery Assessment"
  },
  {
    "slug": "plastic-surgery-waiting-list-card",
    "title": "Plastic Surgery Waiting List Card"
  },
  {
    "slug": "podiatric-surgery-waiting-list-card",
    "title": "Podiatric Surgery Waiting List Card"
  },
  {
    "slug": "post-anaesthesia-care-unit-record",
    "title": "Post-Anaesthesia Care Unit (PACU) Record"
  },
  {
    "slug": "post-operative-report",
    "title": "Post-Operative Report"
  },
  {
    "slug": "post-traumatic-stress-assessment",
    "title": "Post-Traumatic Stress Assessment"
  },
  {
    "slug": "pre-anaesthesia-assessment",
    "title": "Pre-Anaesthesia Assessment"
  },
  {
    "slug": "pre-operative-assessment-by-clinician",
    "title": "Pre-operative Assessment by Clinician"
  },
  {
    "slug": "pre-operative-assessment-by-patient",
    "title": "Pre-operative Assessment by Patient"
  },
  {
    "slug": "predicting-risk-of-cardiovascular-disease-events",
    "title": "Predicting Risk of Cardiovascular Disease Events (PREVENT)"
  },
  {
    "slug": "pregnancy-ultrasound-test-request",
    "title": "Pregnancy Ultrasound Test Request"
  },
  {
    "slug": "prenatal-assessment",
    "title": "Prenatal Assessment"
  },
  {
    "slug": "prescription-request",
    "title": "Prescription Request"
  },
  {
    "slug": "preventive-medicine-waiting-list-card",
    "title": "Preventive Medicine Waiting List Card"
  },
  {
    "slug": "provider-transfer-request",
    "title": "Provider Transfer Request"
  },
  {
    "slug": "psychiatry-assessment",
    "title": "Psychiatry Assessment"
  },
  {
    "slug": "psychiatry-waiting-list-card",
    "title": "Psychiatry Waiting List Card"
  },
  {
    "slug": "psychology-assessment",
    "title": "Psychology Assessment"
  },
  {
    "slug": "public-health-waiting-list-card",
    "title": "Public Health Waiting List Card"
  },
  {
    "slug": "pulmonary-embolism-rule-out-criteria",
    "title": "Pulmonary Embolism Rule-out Criteria (PERC)"
  },
  {
    "slug": "pulmonary-function-test-request",
    "title": "Pulmonary Function Test Request"
  },
  {
    "slug": "pulmonary-function-test-result",
    "title": "Pulmonary Function Test Result"
  },
  {
    "slug": "pulmonology-assessment",
    "title": "Pulmonology Assessment"
  },
  {
    "slug": "qrisk3-cardiovascular-disease-risk-score",
    "title": "QRISK3 Cardiovascular Disease Risk Score"
  },
  {
    "slug": "quick-sequential-organ-failure-assessment",
    "title": "Quick Sequential Organ Failure Assessment (qSOFA)"
  },
  {
    "slug": "radiation-oncology-waiting-list-card",
    "title": "Radiation Oncology Waiting List Card"
  },
  {
    "slug": "radiology-waiting-list-card",
    "title": "Radiology Waiting List Card"
  },
  {
    "slug": "recognition-of-stroke-in-the-emergency-room",
    "title": "Recognition Of Stroke In the Emergency Room (ROSIER)"
  },
  {
    "slug": "recommended-summary-plan-for-emergency-care-and-treatment",
    "title": "Recommended Summary Plan for Emergency Care and Treatment (ReSPECT)"
  },
  {
    "slug": "renal-assessment",
    "title": "Renal Assessment"
  },
  {
    "slug": "research-and-planning-privacy-notice",
    "title": "Research and Planning Privacy Notice"
  },
  {
    "slug": "respiratory-medicine-waiting-list-card",
    "title": "Respiratory Medicine Waiting List Card"
  },
  {
    "slug": "respirology-assessment",
    "title": "Respirology Assessment"
  },
  {
    "slug": "return-to-work",
    "title": "Return to Work"
  },
  {
    "slug": "rheumatology-assessment",
    "title": "Rheumatology Assessment"
  },
  {
    "slug": "rheumatology-waiting-list-card",
    "title": "Rheumatology Waiting List Card"
  },
  {
    "slug": "rockall-score-for-upper-gastrointestinal-bleeding",
    "title": "Rockall Score for Upper Gastrointestinal Bleeding"
  },
  {
    "slug": "screening-program-privacy-notice",
    "title": "Screening Program Privacy Notice"
  },
  {
    "slug": "seasonal-affective-disorder-assessment",
    "title": "Seasonal Affective Disorder Assessment"
  },
  {
    "slug": "semaglutide-assessment",
    "title": "Semaglutide Assessment"
  },
  {
    "slug": "sequential-organ-failure-assessment",
    "title": "Sequential Organ Failure Assessment (SOFA)"
  },
  {
    "slug": "sleep-quality-assessment",
    "title": "Sleep Quality Assessment"
  },
  {
    "slug": "sleep-study-test-request",
    "title": "Sleep Study Test Request"
  },
  {
    "slug": "sleep-study-test-result",
    "title": "Sleep Study Test Result"
  },
  {
    "slug": "soap-note",
    "title": "SOAP Note"
  },
  {
    "slug": "sports-medicine-assessment",
    "title": "Sports Medicine Assessment"
  },
  {
    "slug": "stomatology-waiting-list-card",
    "title": "Stomatology Waiting List Card"
  },
  {
    "slug": "stroke-assessment",
    "title": "Stroke Assessment"
  },
  {
    "slug": "structured-medication-review",
    "title": "Structured Medication Review (SMR)"
  },
  {
    "slug": "substance-abuse-assessment",
    "title": "Substance Abuse Assessment"
  },
  {
    "slug": "sundowner-syndrome-assessment",
    "title": "Sundowner Syndrome Assessment"
  },
  {
    "slug": "systematic-coronary-risk-evaluation-2-diabetes",
    "title": "SCORE2-Diabetes"
  },
  {
    "slug": "thoracic-surgery-waiting-list-card",
    "title": "Thoracic Surgery Waiting List Card"
  },
  {
    "slug": "timi-risk-score-for-acute-coronary-syndrome",
    "title": "TIMI Risk Score for Acute Coronary Syndrome (UA/NSTEMI)"
  },
  {
    "slug": "toxicology-test-request",
    "title": "Toxicology Test Request"
  },
  {
    "slug": "toxicology-test-result",
    "title": "Toxicology Test Result"
  },
  {
    "slug": "tropical-medicine-waiting-list-card",
    "title": "Tropical Medicine Waiting List Card"
  },
  {
    "slug": "tumor-marker-test-request",
    "title": "Tumor Marker Test Request"
  },
  {
    "slug": "tumor-marker-test-result",
    "title": "Tumor Marker Test Result"
  },
  {
    "slug": "ultrasound-test-request",
    "title": "Ultrasound Test Request"
  },
  {
    "slug": "ultrasound-test-result",
    "title": "Ultrasound Test Result"
  },
  {
    "slug": "united-kingdom-driver-and-vehicle-licensing-agency-b1-form",
    "title": "United Kingdom Driver and Vehicle Licensing Agency B1 Form"
  },
  {
    "slug": "united-kingdom-driver-and-vehicle-licensing-agency-m1-form",
    "title": "United Kingdom Driver and Vehicle Licensing Agency M1 Form"
  },
  {
    "slug": "united-kingdom-driver-and-vehicle-licensing-agency-v1-form",
    "title": "United Kingdom Driver and Vehicle Licensing Agency V1 Form"
  },
  {
    "slug": "united-kingdom-lasting-power-of-attorney-for-financial-decisions",
    "title": "United Kingdom Lasting Power of Attorney for Financial Decisions"
  },
  {
    "slug": "united-kingdom-lasting-power-of-attorney-for-health-and-care-decisions",
    "title": "United Kingdom Lasting Power of Attorney for Health and Care Decisions"
  },
  {
    "slug": "united-kingdom-maternity-certificate-mat-b1",
    "title": "United Kingdom Maternity Certificate MAT B1"
  },
  {
    "slug": "united-kingdom-nhs-england-medical-exemption-certificate",
    "title": "UK NHS England Medical Exemption Certificate (FP92A)"
  },
  {
    "slug": "united-kingdom-statement-of-fitness-for-work",
    "title": "United Kingdom Statement of Fitness for Work"
  },
  {
    "slug": "united-states-hipaa-authorization-form",
    "title": "United States HIPAA Authorization Form"
  },
  {
    "slug": "urinalysis-test-request",
    "title": "Urinalysis Test Request"
  },
  {
    "slug": "urinalysis-test-result",
    "title": "Urinalysis Test Result"
  },
  {
    "slug": "urology-assessment",
    "title": "Urology Assessment"
  },
  {
    "slug": "urology-waiting-list-card",
    "title": "Urology Waiting List Card"
  },
  {
    "slug": "vaccinations-assessment",
    "title": "Vaccinations Assessment"
  },
  {
    "slug": "vaccinations-checklist",
    "title": "Vaccinations Checklist"
  },
  {
    "slug": "vascular-surgery-waiting-list-card",
    "title": "Vascular Surgery Waiting List Card"
  },
  {
    "slug": "venereology-waiting-list-card",
    "title": "Venereology Waiting List Card"
  },
  {
    "slug": "ward-round-note",
    "title": "Ward Round Note"
  },
  {
    "slug": "waterlow-pressure-ulcer-risk-assessment",
    "title": "Waterlow Pressure Ulcer Risk Assessment"
  },
  {
    "slug": "wells-score-for-deep-vein-thrombosis",
    "title": "Wells Score for Deep Vein Thrombosis (DVT)"
  },
  {
    "slug": "wells-score-for-pulmonary-embolism",
    "title": "Wells Score for Pulmonary Embolism"
  },
  {
    "slug": "who-acute-referral-form",
    "title": "WHO Acute Referral Form"
  },
  {
    "slug": "who-counter-referral-form",
    "title": "WHO Counter-Referral Form"
  },
  {
    "slug": "who-emergency-first-aid-form",
    "title": "WHO Emergency First Aid Form"
  },
  {
    "slug": "who-emergency-unit-general-form",
    "title": "WHO Emergency Unit Form: General"
  },
  {
    "slug": "who-emergency-unit-trauma-form",
    "title": "WHO Emergency Unit Form: Trauma"
  },
  {
    "slug": "who-prehospital-form",
    "title": "WHO Prehospital Form"
  },
  {
    "slug": "who-surgical-safety-checklist",
    "title": "WHO Surgical Safety Checklist"
  },
  {
    "slug": "workplace-climate-assessment",
    "title": "Workplace Climate Assessment"
  },
  {
    "slug": "workplace-safety-assessment",
    "title": "Workplace Safety Assessment"
  },
  {
    "slug": "workplace-stress-assessment",
    "title": "Workplace Stress Assessment"
  },
  {
    "slug": "x-ray-test-request",
    "title": "X-Ray Test Request"
  },
  {
    "slug": "x-ray-test-result",
    "title": "X-Ray Test Result"
  },
  {
    "slug": "zarit-burden-interview",
    "title": "Zarit Burden Interview (ZBI)"
  }
];
